version: '3.8'

services:
  backend:
    image: ghcr.io/tushar-codespace/glitch-backend:latest
    container_name: glitch-backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    image: ghcr.io/tushar-codespace/glitch-frontend:latest
    container_name: glitch-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
