version: '3.8'

services:
  api-gateway:
    image: ghcr.io/tushar-codespace/glitch-api-gateway:latest
    container_name: glitch-api-gateway
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    image: ghcr.io/tushar-codespace/glitch-frontend:latest
    container_name: glitch-frontend
    ports:
      - "80:80"
    depends_on:
      - api-gateway
    restart: unless-stopped
